### ISSUE TITLE
about data!

### ISSUE THREAD

**Issue by XDUfyf** [eriche2016/mvcnn.pytorch#1]
Hi!
could you please supply your code about convert the modelnet40 to hdf5 files?
my email is evanfeng97@qq.com.
Thanks!

**Comment by eriche2016** [comment]
you can check this file: https://github.com/eriche2016/mvcnn.torch/blob/master/misc/PrepMVDatasetFolder.lua

**Comment by XDUfyf** [comment]
@eriche2016 thank you! I have completed the pre-process code. I have successfully run your code. About 89.5% acc. Thank you very much! ^^
